//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterCodePartnerDetail
    {
        public int Id { get; set; }
        public Nullable<int> CenterCodeId { get; set; }
        public string PartnerName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public string AltContactNumber { get; set; }
        public string AltEmailId { get; set; }
    
        public virtual CenterCode CenterCode { get; set; }
    }
}
