//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterCode
    {
        public CenterCode()
        {
            this.CenterCodePartnerDetails = new HashSet<CenterCodePartnerDetail>();
            this.EmployeeCenters = new HashSet<EmployeeCenter>();
            this.StudentReceiptSerialNoes = new HashSet<StudentReceiptSerialNo>();
            this.StudentSerialNoes = new HashSet<StudentSerialNo>();
            this.StudentWalkInns = new HashSet<StudentWalkInn>();
            this.Group_CentreCode_Setting = new HashSet<Group_CentreCode_Setting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> BranchTypeID { get; set; }
        public Nullable<int> FirmTypeID { get; set; }
        public string CentreCode { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string PhoneNo { get; set; }
        public bool STCompulsory { get; set; }
        public string STRegNo { get; set; }
        public bool Status { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual District District { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Firm Firm { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<CenterCodePartnerDetail> CenterCodePartnerDetails { get; set; }
        public virtual ICollection<EmployeeCenter> EmployeeCenters { get; set; }
        public virtual ICollection<StudentReceiptSerialNo> StudentReceiptSerialNoes { get; set; }
        public virtual ICollection<StudentSerialNo> StudentSerialNoes { get; set; }
        public virtual ICollection<StudentWalkInn> StudentWalkInns { get; set; }
        public virtual ICollection<Group_CentreCode_Setting> Group_CentreCode_Setting { get; set; }
    }
}
