//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.MultiCourseDetails = new HashSet<MultiCourseDetail>();
            this.StudentFeedbacks = new HashSet<StudentFeedback>();
            this.StudentWalkInnCourses = new HashSet<StudentWalkInnCourse>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> SingleFee { get; set; }
        public Nullable<decimal> InstallmentFee { get; set; }
        public string CourseDownloadUrl { get; set; }
        public Nullable<int> MaterialCost { get; set; }
    
        public virtual ICollection<MultiCourseDetail> MultiCourseDetails { get; set; }
        public virtual ICollection<StudentFeedback> StudentFeedbacks { get; set; }
        public virtual ICollection<StudentWalkInnCourse> StudentWalkInnCourses { get; set; }
    }
}
