//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSubTitle
    {
        public CourseSubTitle()
        {
            this.MultiCourses = new HashSet<MultiCourse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CourseSeriesTypeId { get; set; }
        public Nullable<int> CourseTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual CourseSeriesType CourseSeriesType { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual ICollection<MultiCourse> MultiCourses { get; set; }
    }
}
