//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Employees = new HashSet<Employee>();
            this.MenuRoles = new HashSet<MenuRole>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string DesignationName { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<MenuRole> MenuRoles { get; set; }
    }
}
