//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSetting
    {
        public int Id { get; set; }
        public Nullable<int> DiscountRoleId { get; set; }
        public string Group_CentreCode_GroupName { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> CourseSeriesTypeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
    
        public virtual CourseSeriesType CourseSeriesType { get; set; }
    }
}
