//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_CentreCode_Setting
    {
        public int Id { get; set; }
        public Nullable<int> CentreCodeId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual CenterCode CenterCode { get; set; }
    }
}
