//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuRoles = new HashSet<MenuRole>();
        }
    
        public int Id { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    
        public virtual ICollection<MenuRole> MenuRoles { get; set; }
    }
}
