//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiCourse
    {
        public MultiCourse()
        {
            this.MultiCourseDetails = new HashSet<MultiCourseDetail>();
            this.StudentRegistrationCourses = new HashSet<StudentRegistrationCourse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CourseSubTitleId { get; set; }
        public string CourseCode { get; set; }
        public string OldCourseCode { get; set; }
        public string CourseIds { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> SingleFee { get; set; }
        public Nullable<decimal> InstallmentFee { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CourseSubTitle CourseSubTitle { get; set; }
        public virtual ICollection<MultiCourseDetail> MultiCourseDetails { get; set; }
        public virtual ICollection<StudentRegistrationCourse> StudentRegistrationCourses { get; set; }
    }
}
