//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Designations = new HashSet<Designation>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual ICollection<Designation> Designations { get; set; }
    }
}
