//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentWalkInn
    {
        public StudentWalkInn()
        {
            this.StudentRelations = new HashSet<StudentRelation>();
            this.StudentWalkInnCourses = new HashSet<StudentWalkInnCourse>();
            this.StudentRegistrations = new HashSet<StudentRegistration>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CenterCodeId { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> DemoGivenEmpID { get; set; }
        public Nullable<int> QlfnTypeID { get; set; }
        public Nullable<int> QlfnMainID { get; set; }
        public Nullable<int> QlfnSubID { get; set; }
        public Nullable<int> WhyNSID { get; set; }
        public Nullable<int> CRO1ID { get; set; }
        public Nullable<int> CRO2ID { get; set; }
        public string CourseRecommendedIDs { get; set; }
        public string KnowHowNSIDs { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Location { get; set; }
        public string LandlineNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> GuardianType { get; set; }
        public string GuardianName { get; set; }
        public string GuardianContactNo { get; set; }
        public string GuardianOccupation { get; set; }
        public Nullable<int> CandidateStatus { get; set; }
        public Nullable<int> CurrentYear { get; set; }
        public Nullable<int> YearOfCompletion { get; set; }
        public string CollegeAddress { get; set; }
        public Nullable<int> ExpInYears { get; set; }
        public string IndustryType { get; set; }
        public string CompanyAddress { get; set; }
        public bool HasPrevExp { get; set; }
        public string PrevExpPlace { get; set; }
        public string PrevExpYear { get; set; }
        public string PrevExpTrainer { get; set; }
        public Nullable<int> IsPlacementReqd { get; set; }
        public bool IsDemoGiven { get; set; }
        public string Feedback { get; set; }
        public bool JoinStatus { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> BatchPreferred { get; set; }
        public string NotJoiningReason { get; set; }
        public Nullable<int> CROCount { get; set; }
        public Nullable<int> CRO1Percentage { get; set; }
        public Nullable<int> CRO2Percentage { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
    
        public virtual CenterCode CenterCode { get; set; }
        public virtual District District { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual QlfnMain QlfnMain { get; set; }
        public virtual QlfnSub QlfnSub { get; set; }
        public virtual QlfnType QlfnType { get; set; }
        public virtual ICollection<StudentRelation> StudentRelations { get; set; }
        public virtual WhyN WhyN { get; set; }
        public virtual ICollection<StudentWalkInnCourse> StudentWalkInnCourses { get; set; }
        public virtual ICollection<StudentRegistration> StudentRegistrations { get; set; }
    }
}
