//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProjectApproval
    {
        public int Id { get; set; }
        public Nullable<int> StudentFeedbackID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> LeaderID { get; set; }
        public Nullable<bool> IsTrainerApproved { get; set; }
        public Nullable<bool> IsSourceCodeCollected { get; set; }
        public string SourceCodeCollectedDenyReason { get; set; }
        public Nullable<bool> IsCrossChecked { get; set; }
        public string CrossCheckedDenyReason { get; set; }
        public Nullable<bool> IsProjectNotCopied { get; set; }
        public string ProjectIsNotCopiedDenyReason { get; set; }
        public Nullable<bool> IsUploadedSameCourseProjectReport { get; set; }
        public string UploadedSameCourseProjectReportDenyReason { get; set; }
        public Nullable<bool> IsProjectDifferentFromLabExercise { get; set; }
        public string ProjectDifferentFromLabExerciseDenyReason { get; set; }
        public Nullable<System.DateTime> TrainerFeedbackDate { get; set; }
        public Nullable<bool> IsLeaderApproved { get; set; }
        public Nullable<bool> TrainerShownRunningProject { get; set; }
        public string TrainerShownRunningProjectDenialReason { get; set; }
        public Nullable<bool> SourceCodeCollectedFromTrainer { get; set; }
        public string SouceCodeCollectedFromTrainerDenialReason { get; set; }
        public Nullable<System.DateTime> LeaderFeedbackDate { get; set; }
    
        public virtual Employee Trainer { get; set; }
        public virtual Employee Leader { get; set; }
        public virtual StudentFeedback StudentFeedback { get; set; }
    }
}
