//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentReceipt
    {
        public int Id { get; set; }
        public Nullable<int> StudentRegistrationID { get; set; }
        public Nullable<int> CROID { get; set; }
        public string PDCSlip { get; set; }
        public Nullable<int> ModeOfPayment { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string ChNo { get; set; }
        public Nullable<System.DateTime> ChDate { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<double> STPercentage { get; set; }
        public Nullable<int> ST { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> StudentReceiptNo { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual StudentRegistration StudentRegistration { get; set; }
    }
}
