//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRelation
    {
        public int Id { get; set; }
        public int WalkInnID { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
    
        public virtual StudentWalkInn StudentWalkInn { get; set; }
    }
}
