//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public StudentRegistration()
        {
            this.StudentFeedbacks = new HashSet<StudentFeedback>();
            this.StudentLogins = new HashSet<StudentLogin>();
            this.StudentRegistrationCourses = new HashSet<StudentRegistrationCourse>();
            this.StudentReceipts = new HashSet<StudentReceipt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentWalkInnID { get; set; }
        public Nullable<int> RegistrationVenueID { get; set; }
        public Nullable<int> RoundUpID { get; set; }
        public string MultiCourseIDs { get; set; }
        public string RegistrationNumber { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<bool> IsPhotoUploaded { get; set; }
        public Nullable<System.DateTime> PhotoUploadedDate { get; set; }
        public Nullable<bool> IsPhotoVerified { get; set; }
        public Nullable<System.DateTime> PhotoVerifiedDate { get; set; }
        public Nullable<int> FeeMode { get; set; }
        public Nullable<int> NoOfInstallment { get; set; }
        public Nullable<int> TotalDuration { get; set; }
        public Nullable<int> TotalCourseFee { get; set; }
        public Nullable<double> STPercentage { get; set; }
        public Nullable<int> TotalSTAmount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<bool> IsCertificateIssued { get; set; }
        public Nullable<bool> IsPhotoRejected { get; set; }
        public string PhotoRejectedReason { get; set; }
        public Nullable<System.DateTime> PhotoRejectedDate { get; set; }
        public string DiscountReason { get; set; }
        public Nullable<int> DiscountOfficalId { get; set; }
    
        public virtual ICollection<StudentFeedback> StudentFeedbacks { get; set; }
        public virtual ICollection<StudentLogin> StudentLogins { get; set; }
        public virtual StudentWalkInn StudentWalkInn { get; set; }
        public virtual ICollection<StudentRegistrationCourse> StudentRegistrationCourses { get; set; }
        public virtual ICollection<StudentReceipt> StudentReceipts { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
