//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeedback
    {
        public StudentFeedback()
        {
            this.StudentProjectApprovals = new HashSet<StudentProjectApproval>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentRegistrationId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> TotalCourseAmount { get; set; }
        public Nullable<bool> IsFeedbackGiven { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public Nullable<System.DateTime> CourseStartDate { get; set; }
        public Nullable<System.DateTime> CourseEndDate { get; set; }
        public Nullable<bool> IsHardCopyRequired { get; set; }
        public Nullable<int> LearningEnvironmentRating { get; set; }
        public string LearningEnvironmentDislikeReason { get; set; }
        public Nullable<int> EquipmentRating { get; set; }
        public string EquipmentDislikeReason { get; set; }
        public Nullable<int> CiricullumRating { get; set; }
        public string CiricullumDislikeReason { get; set; }
        public Nullable<int> InstructorPreparationRating { get; set; }
        public string InstructorPreparationDislikeReason { get; set; }
        public Nullable<int> InstructorExplanationRating { get; set; }
        public string InstructorExplanationDislikeReason { get; set; }
        public Nullable<int> InstructorClassStartTimeRating { get; set; }
        public string InstructorClassStartTimeDislikeReason { get; set; }
        public Nullable<int> InstructorProjectSupportRating { get; set; }
        public string InstructorProjectSupportDislikeReason { get; set; }
        public Nullable<int> OverallExperienceRating { get; set; }
        public string OverallExperienceDislikeReason { get; set; }
        public Nullable<int> CustomerCareRating { get; set; }
        public string CustomerCareDislikeReason { get; set; }
        public Nullable<int> CourseRecommendationRating { get; set; }
        public string CourseRecommendationDislikeReason { get; set; }
        public Nullable<bool> IsCourseInterestedInFuture { get; set; }
        public string PreferredCourseIds { get; set; }
        public string PreferredCourseName { get; set; }
        public Nullable<bool> IsProjectUploaded { get; set; }
        public Nullable<System.DateTime> ProjectUploadDate { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectUploadURL { get; set; }
        public Nullable<bool> IsTrainerVerified { get; set; }
        public Nullable<bool> IsLeaderVerified { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<StudentProjectApproval> StudentProjectApprovals { get; set; }
        public virtual StudentRegistration StudentRegistration { get; set; }
    }
}
