//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<bool> IsFirstTimeLogin { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
